services:
  hits:
    image: ghcr.io/mat-ocl/hits:latest
    container_name: hits
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://hits_redis:6379
    depends_on:
      hits_redis:
        condition: service_healthy

  hits_redis:
    image: redis:7-alpine
    container_name: hits_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
